apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: webapp-ns
  name: webapp-frontend-ingress
  annotations:
    deployment.kubernetes.io/revision: "1"
  labels:
    name: webapp-frontend-ingress
spec:
  rules:
  - http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: webapp-frontend-svc
            port: 
              number: 80
